baseURL: "https://clsnyder.github.io/"
languageCode: "en-us"
title: "Kaizen"
theme: "ananke"

params:
  homeInfoParams:
    Title: "Welcome to Kaizen"
    Content: "Continuous Improvement in Public."

  socialIcons:
    - name: github
      url: "https://github.com/clsnyder"

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
